#pragma config(Sensor, S1,     c1,             sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     c2,             sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     c3,             sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define blue 2
#define yellow 4
#define red 5
#define white 6
#define INF 100000

int nMotorSpeedSetting = 25, vertex = 0, count = 0, row = 0,val,r = 5,c= 5;
int S[5][5], dt[5][5];
char OX[5][5];

void turnLeft();
void turnRight();
int max(int a, int b);
void go();
void completeSearch();
void goLeft();
void goUp();
void stopMotor();
void retrace();

int max (int a, int b)
{
   return a>b ? a : b;
}


void turnLeft()
{
    setMotorSpeed(lm, 40);
    setMotorSpeed(rm, 40);
    sleep(200);
    while( getColorName(c1) != 4)
    {
        setMotorSpeed(lm, -nMotorSpeedSetting * 4/10);
        setMotorSpeed(rm, nMotorSpeedSetting * 4/10);
        sleep(10);
    }

    while( getColorName(c2) != 4)
    {
        setMotorSpeed(lm, -nMotorSpeedSetting * 4/10);
        setMotorSpeed(rm, nMotorSpeedSetting * 4/10);
    }
    while(getColorName(c2) == 4){
        setMotorSpeed(lm, -nMotorSpeedSetting * 4/10);
        setMotorSpeed(rm, nMotorSpeedSetting * 4/10);
    }
    setMotorSpeed(lm, 0);
    setMotorSpeed(rm, 0);
    sleep(100);
}

void turnRight()
{
    setMotorSpeed(lm, 40);
    setMotorSpeed(rm, 40);
    sleep(200);
    while( getColorName(c3) != 4)
    {
        setMotorSpeed(lm, nMotorSpeedSetting * 4/10);
        setMotorSpeed(rm, -nMotorSpeedSetting * 4/10);
    }
    while( getColorName(c2) != 4)
    {
        setMotorSpeed(lm, nMotorSpeedSetting * 4/10);
        setMotorSpeed(rm, -nMotorSpeedSetting * 4/10);
    }
    while(getColorName(c2) == 4){
        setMotorSpeed(lm, nMotorSpeedSetting * 4/10);
        setMotorSpeed(rm, -nMotorSpeedSetting * 4/10);
    }
    while(getColorName(c2)!=4)
    {
        setMotorSpeed(rm,nMotorSpeedSetting * 4/10);
        setMotorSpeed(lm,-nMotorSpeedSetting * 4/10);
    }
    setMotorSpeed(lm, 0);
    setMotorSpeed(rm, 0);
    sleep(100);
}

void stopMotor(){
    setMotorSpeed(lm,0);
    setMotorSpeed(rm,0);
}

void goUp()
{
    if(c!=0) 
    {
        setMotorSpeed(lm,40);
        setMotorSpeed(rm,40);
        sleep(50);
        turnRight();
    }
    count=0;
    while(true)
    {
        retrace();
        if(count == 1)
        {
            if(c==0){
                break;
            }
            setMotorSpeed(lm,40);
            setMotorSpeed(rm,40);
            sleep(90);
            turnLeft();
            while(getColorName(c1)==6){
                if(getColorName(c2) != white)
                {
                    setMotorSpeed(lm,-(nMotorSpeedSetting + val)/2);
                    setMotorSpeed(rm,-(nMotorSpeedSetting - val)/4);
                }
                //if c2 is on white turn right
                else
                {
                    setMotorSpeed(lm,-(nMotorSpeedSetting - val)/4);
                    setMotorSpeed(rm,-(nMotorSpeedSetting + val));
                }
            }
            while(getColorName(c1)!=6){
               if(getColorName(c2) != white)
                {
                    setMotorSpeed(lm,(nMotorSpeedSetting - val)/4);
                    setMotorSpeed(rm,(nMotorSpeedSetting + val)/2);
                }
                //if c2 is on white turn right
                else
                {
                    setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
                    setMotorSpeed(rm,(nMotorSpeedSetting - val)/4);
                }
            }
            stopMotor();
            sleep(200);
            break;
        }
    }
    r=r-1; 
}

void goLeft()
{  
    c=c-1;
    count = 0;

    while(true)
    {
        retrace();
        if(count == 1)
        {
            break;
        }
    }
    stopMotor();
    sleep(100);

    if(c==0){
        turnRight();
    }
}

void retrace(){
    val = 5;

    //if c2 is on color turn left
    if(getColorName(c2) != white)
    {
        setMotorSpeed(lm,(nMotorSpeedSetting - val)/2);
        setMotorSpeed(rm,(nMotorSpeedSetting + val)/2);
    }
    //if c2 is on white turn right
    else
    {
        setMotorSpeed(lm,(nMotorSpeedSetting + val));
        setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
    }
        
    if((r==0 || c==4) && getColorName(c1) !=6){
        while(getColorName(c2)==6){
            setMotorSpeed(lm,(nMotorSpeedSetting + val));
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
        }
        while(getColorName(c1) !=6){
            setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
        }
        count=count+1;
        stopMotor();
        playTone(440,20);
        sleep(100);
    }


    else if((r!=0&& c!=4) && getColorName(c3) !=6 ){
        while(getColorName(c2)==6){
            setMotorSpeed(lm,(nMotorSpeedSetting + val));
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
        }
        while(getColorName(c3) !=6){
            setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
        }
        count=count+1;
        stopMotor();
        playTone(440,20);
        sleep(100);
    } 
   
}

void completeSearch()
{
    int checksize = 0;
   while(true)
   {
        go();
        if(row == 0 && count == 4 && checksize == 0)
        {
            {
                stopMotor();
                sleep(100);
                setMotorSpeed(lm, 20);
                setMotorSpeed(rm, 20);
                sleep(400);
                stopMotor();
                sleep(100);
            }
            if(getColorName(c2) != white)
            {
                c = 4;
                r = 3;
                setMotorSpeed(lm, -20);
                setMotorSpeed(rm, -20);
                sleep(200);
                stopMotor();
                sleep(100);
            }
            else
            {
                c = 3;
                r = 4;
                setMotorSpeed(lm, -20);
                setMotorSpeed(rm, -20);
                sleep(300);
                stopMotor();
                sleep(100);
            }    
            checksize++;
        }   

        if(count == c+1)
        {
            if(row == r) return;
            if(row%2 ==0)
            {
                turnRight();
            }
            else
            {
                turnLeft();
            }

            count=0;
            row=row+1;

            stopMotor();
            sleep(500);


            if(row%2 == 0)
            {
                while(getColorName(c1)== 6) {
                    //if on color turn left
                    if(getColorName(c2) != white)
                    {
                        setMotorSpeed(lm,(nMotorSpeedSetting - val)/2);
                        setMotorSpeed(rm,(nMotorSpeedSetting + val)/2);
                    }
                    //if on white turn right
                    else
                    {
                        setMotorSpeed(lm,(nMotorSpeedSetting + val));
                        setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
                    }
                }
                go();
                turnLeft();
            }
            else
            {
                while(getColorName(c3)== 6) {
                    //if on color turn left
                    if(getColorName(c2) != white)
                    {
                        setMotorSpeed(lm,(nMotorSpeedSetting - val)/2);
                        setMotorSpeed(rm,(nMotorSpeedSetting + val)/2);
                    }
                    //if on white turn right
                    else
                    {
                        setMotorSpeed(lm,(nMotorSpeedSetting + val));
                        setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
                    }
                }
                go();
                turnRight();
            }
        }
    }
}

//Except row is 0, if row is odd then use right,if row is even then use left 
void go(){
    val = 5;

    //if c2 is on color turn left
    if(getColorName(c2) != white)
    {
        setMotorSpeed(lm,nMotorSpeedSetting - val);
        setMotorSpeed(rm,nMotorSpeedSetting + val);
    }
    //if c2 is on white turn right
    else
    {
        setMotorSpeed(lm,nMotorSpeedSetting + val);
        setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
    }

    // vertex on right side && row ==0 or row is odd number or 0
    if((row==0 || row %2 == 1) && getColorName(c3) !=6){
        int check=0;
        //get c2 on the line
        while(getColorName(c2)==6){
            setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/8);
            sleep(80);
        }
        //while c2 is not white turn right for color
        while(getColorName(c2)!=6 && check < 2){
            setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/8);
            sleep(120);
            //?
            if(getColorName(c2) == red) 
            {
                if (row%2 == 0) S[row][count] = 1;
                else S[row][4-count] = 1;
                playSound(soundBeepBeep); 
                check++;
                sleep(50);
            }
            else if (getColorName(c2) == blue){
                if (row%2 == 0) S[row][count] = -1;
                else S[row][4-count] = -1;
                playTone(220,20);
                check++;
                sleep(50);
            }
            else{
                if (row%2 == 0) S[row][count] = 0;
                else S[row][4-count] = 0;
                playTone(440,20);
                check++;
                sleep(50);
            }
        }

        //if blue then turn back
        /*if(getColorName(c2)==6 && bcolor == -1){
            while(getColorName(c2)==6){ 
                setMotorSpeed(lm,-(nMotorSpeedSetting + val)/2);
                setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
                sleep(50);
            }
            setMotorSpeed(lm,(nMotorSpeedSetting - val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting + val));
            sleep(120);
        }*/

        while(getColorName(c3) !=6){
            //if on color turn left
            if(getColorName(c2) != white)
            {
                setMotorSpeed(lm,nMotorSpeedSetting - val);
                setMotorSpeed(rm,nMotorSpeedSetting + val);
            }
            //if on white turn right
            else
            {
                setMotorSpeed(lm,nMotorSpeedSetting + val);
                setMotorSpeed(rm,nMotorSpeedSetting - val);
            }
        }
        vertex=1;
    }

    // vertex on left side && row is even number
    else if(row %2 == 0 && row !=0 && getColorName(c1) !=6){
        int check=0;
        while(getColorName(c2)==6){
            setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/8);
            sleep(80);
        }


       while(getColorName(c2)!=6 && check < 2){
            setMotorSpeed(lm,(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting - val)/8);
            sleep(120);
            //?
            if(getColorName(c2) == red) 
            {
                if (row%2 == 0) S[row][count] = 1;
                else S[row][4-count] = 1;
                playSound(soundBeepBeep); 
                check++;
                sleep(50);
            }
            else if (getColorName(c2) == blue){
                if (row%2 == 0) S[row][count] = -1;
                else S[row][4-count] = -1;
                playTone(220,20);
                check++;
                sleep(50);
            }
            else{
                if (row%2 == 0) S[row][count] = 0;
                else S[row][4-count] = 0;
                playTone(440,20);
                check++;
                sleep(50);
            }
        }


        /*if(getColorName(c2)==6 && bcolor==-1){
            while(getColorName(c2)==6){
                setMotorSpeed(lm,-(nMotorSpeedSetting + val)/2);
                setMotorSpeed(rm,(nMotorSpeedSetting - val)/2);
                sleep(50);
            }
            setMotorSpeed(lm,(nMotorSpeedSetting - val)/2);
            setMotorSpeed(rm,(nMotorSpeedSetting + val));
            sleep(120);
        }*/

        while(getColorName(c1) !=6){
            //if on color turn left
            if(getColorName(c2) != white)
            {
                setMotorSpeed(lm,nMotorSpeedSetting - val);
                setMotorSpeed(rm,nMotorSpeedSetting + val);
            }
            //if on white turn right
            else
            {
                setMotorSpeed(lm,nMotorSpeedSetting + val);
                setMotorSpeed(rm,nMotorSpeedSetting - val);
            }
        }
        vertex=1;
    }    

    else vertex = 0;

    if(vertex ==1){
        count=count+1;
    }
}

void init_S()
{
    for(int i = 0; i<5; i++)
       for(int j = 0; j<5; j++)
          S[i][j] = INF;   
}

void patch_print()
{
    if(c==3){
        for(int i = 1; i<5; i+=2)
        {
            for(int j = 0; j<4; j++)
            {
                S[i][j] = S[i][j+1];
            }
            S[i][4] = INF;
        }
    }

    for(int i = 0; i<5; i++)
    {
            for(int j = 0; j<5; j++)
            {
            if(S[i][j] == 1) OX[i][j] = 'O';
            else if(S[i][j] == 0) OX[i][j] = '+';
            else if(S[i][j] == -1) OX[i][j] = 'X';
            else OX[i][j] = 'F';
            }
    }



    for(int i = 0; i<5; i++)
       for(int j = 0; j<5; j++)
               if(OX[i][j] != 'F') displayBigStringAt((j+1)*20, 130-(i+1)*20, "%c ", OX[i][j]);
    sleep(5000);
}


task main(){
    while(getButtonPress(1)==0) sleep(10);
    init_S();
    completeSearch();
    playTone(240,20);
    sleep(200);
    
 

    stopMotor();
    patch_print();  
    eraseDisplay();
    if((c==4))
    {
        
        turnLeft(); 
        count = 0;
        row=row+1;
        sleep(50);
        while(true){
            go();
            if(count==4){
                break;
            }
        }
        stopMotor();
        sleep(500);
    }

    //return 
    setMotorSpeed(lm,40);
    setMotorSpeed(rm,40);
    sleep(100);
    turnRight();
    while(getColorName(c3)==white){
        if(getColorName(c2) != white)
        {
            setMotorSpeed(lm,-(nMotorSpeedSetting - val)/4);
            setMotorSpeed(rm,-(nMotorSpeedSetting + val)/2);
        }
        //if c2 is on white turn right
        else
        {
            setMotorSpeed(lm,-(nMotorSpeedSetting + val)/2);
            setMotorSpeed(rm,-(nMotorSpeedSetting - val)/4);
        }
    }
    while(getColorName(c3)!=6){
        setMotorSpeed(lm,+(nMotorSpeedSetting + val)/4);
        setMotorSpeed(rm,+(nMotorSpeedSetting + val));
    }
    while(getColorName(c2) == white){
        setMotorSpeed(lm,(nMotorSpeedSetting + val)/4);
        setMotorSpeed(rm,(nMotorSpeedSetting + val));
        sleep(100);
    }
    stopMotor();
    sleep(500);
    for( int i = 0; i<r+1 ;i++){
        for ( int j = 0; j<c+1 ;j++){
            if(i==0 && j==0) dt[i][j]=S[i][j];
            else if(i==0) dt[i][j] = dt[i][j-1]+S[i][j];
            else if(j==0) dt[i][j] = dt[i-1][j]+S[i][j];
            else dt[i][j]= max(dt[i-1][j],dt[i][j-1])+S[i][j];
        }
    }
    sleep(500);
    int score = dt[r][c];    
   
    while(r != 0 || c!= 0){
        if(r==0) goLeft();
        else if(c ==0) goUp();
        else if(dt[r-1][c] > dt[r][c-1]) goUp();
        else goLeft();
    }

    playTone(240,20);
    stopMotor();

    displayBigTextLine(1, "score : %d", score);    
    sleep(200);

    while(getButtonPress(1)==0) sleep(10);
}